---
# roles/webserver/tasks/main.yml

- name: Install Apache and PHP
  ansible.builtin.include_tasks: install.yml

- name: Deploy website
  ansible.builtin.include_tasks: deploy.yml

- name: Configure Firewall
  ansible.builtin.include_tasks: firewall.yml
